### ISSUE TITLE
the error when i download Indiana-University for the RRG task

### ISSUE THREAD

**Issue by mylu2021** [jbdel/vilmedic#14]
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1Cv9u3ZoOb8hZVcObMqHRNxsoAdZpYGt4 

Unzipping...
Traceback (most recent call last):
  File "/home/mylu/anaconda3/envs/pytorch181/bin/vilmedic-download", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/mylu/packages/vilmedic/bin/scripts/vilmedic-download", line 88, in <module>
    download_images(data_name=key, file_id=file_id, unzip_dir=os.path.join(DATA_DIR, "images"))
  File "/data/mylu/packages/vilmedic/bin/scripts/vilmedic-download", line 31, in download_images
    with zipfile.ZipFile(zip_name, 'r') as zf:
  File "/home/mylu/anaconda3/envs/pytorch181/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/indiana-images-512.zip'

ask for help

**Comment by jbdel** [comment]
the link has been fixed
