### ISSUE TITLE
Encounter error in get_chexbert_label.py 

### ISSUE THREAD

**Issue by yuanpinz** [jbdel/vilmedic#22]
$ python get_chexbert_label.py SELFUP/mimic-cxr/train.report.tok 
Traceback (most recent call last):
  File "get_chexbert_label.py", line 6, in <module>
    from vilmedic.blocks.scorers import CheXbert
  File "/vilmedic/vilmedic/__init__.py", line 13, in <module>
    from .zoo.modeling_auto import AutoModel
  File "/vilmedic/vilmedic/zoo/modeling_auto.py", line 11, in <module>
    from ..models import *
  File "/vilmedic/vilmedic/models/__init__.py", line 9, in <module>
    from vilmedic.models.rrs.RRS_HF import RRS_HF
  File "/vilmedic/vilmedic/models/rrs/RRS_HF.py", line 10, in <module>
    from vilmedic.blocks.huggingface.encoder_decoder.text_evaluation import evaluation
  File "/vilmedic/vilmedic/blocks/huggingface/encoder_decoder/text_evaluation.py", line 4, in <module>
    import voxel as vx
ModuleNotFoundError: No module named 'voxel'

**Comment by yuanpinz** [comment]
Solved after installing pyvoxel manually.
