### ISSUE TITLE
Unable to download and access models zoo

### ISSUE THREAD

**Issue by fbrynpk** [jbdel/vilmedic#25]
Hi, thank you for the code and an amazing work to access some of the pre-trained model, but when I tried to run the code, I was unable to download the model from the models zoo and end up with an empty folder, could you help me understand as to why this happened and maybe help fix this? I tried to run the code according to the Vilmedic website quick start guide!

Downloading in C:\Users\User\AppData\Local\vilmedic\vilmedic\Cache\zoo\models
Retrieving folder list
Traceback (most recent call last):
  File "c:/Users/User/Desktop/vilmedic/convirt.py", line 2, in <module>
    model, processor = AutoModel.from_pretrained("rrg/biomed-roberta-baseline-mimic")
  File "C:\Users\User\anaconda3\envs\vilmedic\lib\site-packages\vilmedic\zoo\modeling_auto.py", line 69, in from_pretrained
    assert len(checkpoint) == 1, "More than one or no checkpoint found"
AssertionError: More than one or no checkpoint found

**Comment by yihp** [comment]
hello
![Uploading image.png…]()

**Comment by yihp** [comment]
![Uploading LOGO.png…]()

**Comment by yihp** [comment]
![Uploading LOGO.png…]()

**Comment by ddaanial** [comment]
I have the same issue.
